# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iThoughtsFileFormat' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for iThoughtsFileFormat
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'Zip', '~> 1.1'
end
